# Config.py
# Program config, automagically generated by install.py
# Published under the Apache License 2.0, maintained by James Bolton (james@neojames.me)

username = "test"
password = "gAAAAABeEUaeYGPQnNqSQ0PlG4gn9P0IW_nRL8OjC10WQwfsbwCs3nxd7qBO3TXbRNVGv-iolpAZAO0krBM0ohtYkFv7wdzUbQ=="
salt = "pcqbwrwsbudwkndo"
passkey = "uxefsdtgijinhxwqwlxhtnnwjhllkuwe"
