# Install.py
# Writes program config file.
# Published under the Apache License 2.0, maintained by James Bolton (james@neojames.me)

import base64
import os
import random
import shutil
import string
from datetime import datetime

import questionary
from cryptography.fernet import Fernet
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC

print('Warning! Continuing to run this program will overwrite the config file. A backup will be created in the '
      'backups folder.')

cont = questionary.confirm("Do you wish to continue?").ask()

if cont == 1:
    print('Backing up now!')
    today = datetime.now()
    file = 'backups/config_' + today.strftime("%b-%d-%Y-%H-%M") + '.py'
    if not os.path.exists('backups'):
        os.mkdir('backups')
    if os.path.exists('config.py'):
        shutil.move('config.py', file)
elif cont == 0:
    exit(0)
else:
    exit(0)

with open('config.py', 'a+') as file:
    file.write('# Config.py\n')
    file.write('# Program config, automagically generated by install.py\n')
    file.write('# Published under the Apache License 2.0, maintained by James Bolton (james@neojames.me)\n\n')

username = questionary.text("What's your MySchedule username?").ask()
password = questionary.password("What's your MySchedule password").ask()


def randomString(stringLength=10):
    """Generate a random string of fixed length """
    letters = string.ascii_lowercase
    return ''.join(random.choice(letters) for i in range(stringLength))


password = password.encode()

salt = randomString(16).encode()
passkey = randomString(32).encode()

kdf = PBKDF2HMAC(
    algorithm=hashes.SHA256(),
    length=32,
    salt=salt,
    iterations=100000,
    backend=default_backend()
)
key = base64.urlsafe_b64encode(kdf.derive(passkey))

key = Fernet(key)
password = key.encrypt(password)
password = password.decode()
salt = salt.decode()
passkey = passkey.decode()

with open('config.py', 'a+') as file:
    file.write('username = "' + username + '"\n')
    file.write('password = "' + password + '"\n')
    file.write('salt = "' + salt + '"\n')
    file.write('passkey = "' + passkey + '"')
exit(1)

# f = open("config.py", "w")
